# vim: set ft=yaml sw=2 ts=2 et :

image: $CI_REGISTRY/docker/rust/rust:alpine

stages:
  - test
  - build

cache:
  paths:
    - .cargo
    - target/

test:cargo:
  stage: test
  tags:
    - docker
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo tarpaulin --verbose --out Xml
  artifacts:
    reports:
      cobertura: cobertura.xml

build:
  stage: build
  tags:
    - docker
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/bdup

