# vim: set ft=yaml sw=2 ts=2 et :

image: $CI_REGISTRY/docker/rust/rust:alpine

test:cargo:
  tags:
    - docker
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose

