# vim: set ft=yaml ts=2 sw=2 et :
---

name: Cargo audit

"on":
  workflow_dispatch: {}
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  schedule:
    - cron: "33 6 * * 1"

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      checks: write

    steps:
      - uses: actions/checkout@v3

      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

